project_id = "vitapulse"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[db.migrations]
enabled = true
schema_paths = []

[auth]
enabled = true
site_url = "http://127.0.0.1:4173"
additional_redirect_urls = ["http://localhost:4173"]
enable_signup = true
